/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desafio;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author David
 */
public class Malla extends javax.swing.JFrame {

    /**
     * Creates new form Dominio
     */
    JFrame frame;
    ImageIcon icon;

    public Malla() {
        initComponents();
        icon = new ImageIcon(getClass().getResource("/resources/imagenes/icono.png"));
        setIconImage(icon.getImage());
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
        ImageIcon imagen = new ImageIcon(getClass().getResource("/resources/gif/GifMalla.gif"));
        Icon img = new ImageIcon(imagen.getImage().getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_DEFAULT));
        jLabel3.setIcon(img);
        ImageIcon imagenb = new ImageIcon(getClass().getResource("/resources/iconos/b1.png"));
        Icon imgb = new ImageIcon(imagenb.getImage().getScaledInstance(L11.getWidth(), L11.getHeight(), Image.SCALE_SMOOTH));
        L11.setIcon(imgb);
        resize(800, 450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L11.setText("jLabel1");
        L11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L11MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                L11MousePressed(evt);
            }
        });
        getContentPane().add(L11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 100));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 300, 300));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/fondos/FondoDom.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void L11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L11MouseEntered
        // TODO add your handling code here:
        ImageIcon imagenb = new ImageIcon(getClass().getResource("/resources/iconos/b2.png"));
        Icon imgb = new ImageIcon(imagenb.getImage().getScaledInstance(L11.getWidth(), L11.getHeight(), Image.SCALE_SMOOTH));
        L11.setIcon(imgb);
    }//GEN-LAST:event_L11MouseEntered

    private void L11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L11MouseExited
        // TODO add your handling code here:
      ImageIcon imagenb = new ImageIcon(getClass().getResource("/resources/iconos/b1.png"));
        Icon imgb = new ImageIcon(imagenb.getImage().getScaledInstance(L11.getWidth(), L11.getHeight(), Image.SCALE_SMOOTH));
        L11.setIcon(imgb);
    }//GEN-LAST:event_L11MouseExited

    private void L11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L11MousePressed
        // TODO add your handling code here:
        new NewJFrame().show();
        dispose();
    }//GEN-LAST:event_L11MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Malla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Malla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Malla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Malla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Malla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
